### ISSUE TITLE
Missing parent maven project

### ISSUE THREAD

**Issue by sdybiec** [tfreese/base-components#1]
Nice work. Impressive framework. Trying to get it to build, but the child POMs in each of the projects are referencing a non-existent the parent maven project.

```
<parent>
        <groupId>de.freese</groupId>
        <artifactId>maven-parent</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath /> 
    </parent>
```

**Comment by tfreese** [comment]
You don't need the parent pom.
It is in a private project.
Just remove it and configure the version properties.

**Comment by sdybiec** [comment]
Will do.  I started adding all the versions into the poms, but there were a lot of them, so I thought I'd see if the parent was available.  Thank again for sharing your great work.
